language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"
  - "nightly"

before_install:
  - python3 --version || python --version
  - pip3 install --upgrade pip

install:
  - pip3 install .

script:
  - python3 setup.py pytest
